# Generated by Django 4.2.4 on 2023-08-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('datetime', models.DateField(default='2000-11-29', primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateTimeField(default='2000-11-29', unique=True, verbose_name='')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('description', models.CharField(max_length=200, verbose_name='')),
                ('color', models.CharField(default='Yellow', max_length=200, verbose_name='')),
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
