# Generated by Django 4.2.4 on 2023-08-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_day_event_color_routine_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='repeat',
            field=models.JSONField(default=dict),
        ),
    ]
